server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: recruiterModule
        uri: http://recruiter-service:8081/graphiql?path=
        predicates:
        - Path=/recruiter
      - id: jobModule
        uri: http://job-service:8082/graphiql?path=
        predicates:
        - Path=/job
