server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: recruiter
        uri: http://recruiter-service:8081
        predicates:
        - Path=/recruiter

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF